import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";
import Link from "next/link";
import Spline_layout from "@/components/spline";

const inter = Inter({ subsets: ["latin"] });

function typeName() {
  return "Test Str";
}

export default function Home() {
  const name = typeName();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.h_100React}>
        <Spline_layout />
      </div>
      {/* <main className={styles.main}>
        <Link href="/tammer">Tammer {name}</Link>
        <div className={styles.h_100React}>
        </div>
        <Card title="React props" />        
      </main> */}
    </>
  );
}
